### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by CyanoFresh** [Polymer/paper-elements#25]
Hello. Sorry for my English.
I can't install paper elements via bower. Log: http://pastebin.com/D8zUhMs6

**Comment by cdata** [comment]
It looks like you might have a permissions problem:

```sh
bower EACCES EACCES, mkdir '/var/www/test.solomaha.me/bower_components/paper-elements'
```

Is it possible that permissions are set incorrectly somewhere along the path for `/var/www/test.solomaha.me/bower_components/paper-elements`?

**Comment by CyanoFresh** [comment]
Yes. It was permission error. Sorry. Thank you
